services:
  express:
    container_name: tpia_express
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT-3000}:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - CHROMADB_HOST=http://chromadb:${CHROMADB_PORT-8000}
      - NODE_ENV=${NODE_ENV-dev}
      - API_KEY=${API_KEY}
      - DEBUG_MODE=${DEBUG_MODE-false}
      - BACKEND_PORT=${BACKEND_PORT-3000}
    depends_on:
      - chromadb

  chromadb:
    container_name: tpia_chroma
    image: chromadb/chroma
    ports:
      - ${CHROMADB_PORT-8000}:8000
    volumes:
      - ${CHROMADB_DATA_PATH-./chromadb_data}:/data
    environment:
      - IS_PERSISTENT=true
      - PERSISTENT_DIRECTORY=/data
      - ANONYMIZED_TELEMETRY=true

  react:
    container_name: tpia_react
    build:
      context: ./react/
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT-3030}:3030
    volumes:
      - ./react:/app
      - /react/node_modules
    environment:
      - NODE_ENV=${NODE_ENV-dev}
      - API_KEY=${API_KEY}
      - DEBUG_MODE=${DEBUG_MODE-false}
      - FRONTEND_PORT=${FRONTEND_PORT-3030}
      - BACKEND_PORT=${BACKEND_PORT-3000}
    depends_on:
      - express
